<?php

declare(strict_types=1);

namespace CometCMS\Controllers;

use CometCMS\Core\Http;
use CometCMS\Core\Security;

final class AdminController
{
    public function __construct(private readonly Http $http) {}

    public function shell(): never
    {
        $assets = $this->viteAssets();

        if ($assets['missing']) {
            http_response_code(503);
            header('Content-Type: text/html; charset=utf-8');
            echo '<!doctype html><html lang="en"><head><meta charset="utf-8"><title>CometCMS</title>'
                . '<style>body{font:15px system-ui,sans-serif;padding:3rem;max-width:600px;margin:auto}code,pre{background:#f0f0f0;padding:2px 6px;border-radius:4px}</style>'
                . '</head><body><h1>CometCMS Admin</h1>'
                . '<p>The admin UI has not been built yet. Run <code>make dev</code> from the project root for development, or deploy the output generated by <code>make build</code>.</p>'
                . '</body></html>';
            exit;
        }

        $csrf = Security::csrfToken();
        $name = Security::e((string) comet_config('app.name', 'CometCMS'));

        $links = implode('', array_map(
            fn(string $css): string => '<link rel="stylesheet" href="' . Security::e($css) . '">',
            $assets['styles']
        ));

        $scripts = implode('', array_map(
            fn(string $js): string => '<script type="module" src="' . Security::e($js) . '"></script>',
            $assets['scripts']
        ));

        http_response_code(200);
        header('Content-Type: text/html; charset=utf-8');
        echo '<!doctype html>'
            . '<html lang="en">'
            . '<head>'
            . '<meta charset="utf-8">'
            . '<meta name="viewport" content="width=device-width,initial-scale=1">'
            . '<meta name="csrf-token" content="' . Security::e($csrf) . '">'
            . '<title>' . $name . '</title>'
            . $links
            . '</head>'
            . '<body>'
            . '<div id="app"></div>'
            . $scripts
            . '</body>'
            . '</html>';
        exit;
    }

    // -------------------------------------------------------------------------
    // Vite asset resolution
    // -------------------------------------------------------------------------

    private function viteAssets(): array
    {
        // Dev mode: Vite dev server writes a hot-file with its URL.
        $hotFile = COMET_ROOT . '/.vite-hot';

        if (is_file($hotFile)) {
            $url = rtrim((string) file_get_contents($hotFile));

            return [
                'scripts' => [$url . '/@vite/client', $url . '/admin/src/main.js'],
                'styles' => [],
                'missing' => false,
            ];
        }

        // Production mode: read hashed filenames from Vite's manifest.
        $manifest = COMET_ROOT . '/admin/.vite/manifest.json';

        if (!is_file($manifest)) {
            return ['scripts' => [], 'styles' => [], 'missing' => true];
        }

        $data = json_decode((string) file_get_contents($manifest), true);

        if (!is_array($data)) {
            return ['scripts' => [], 'styles' => [], 'missing' => true];
        }

        $entry = $data['src/main.js'] ?? null;

        if (!is_array($entry)) {
            return ['scripts' => [], 'styles' => [], 'missing' => true];
        }

        $base = $this->http->url('/admin/');

        return [
            'scripts' => [$base . $entry['file']],
            'styles' => array_map(fn(string $css): string => $base . $css, $entry['css'] ?? []),
            'missing' => false,
        ];
    }
}
